.Dd $Mdocdate$
.Dt DSBSu
.Sh ABOUT
.Nm DSBSu
is a Qt frontend to su(1).
.Sh INSTALLATION
.Ss Dependencies
.Nm
depends on
.Em devel/qt5-buildtools , devel/qt5-core , devel/qt5-linguisttools ,
.Em devel/qt5-qmake , x11-toolkits/qt5-gui ,
and
.Em x11-toolkits/qt5-widgets

.Ss Getting the source code
.Bd -literal
# git clone https://github.com/mrclksr/DSBSu.git
.Ss Building and installation
.Bd -literal
# cd DSBSu && qmake
# make && make install
.Ed
.Sh USAGE
.Nm dsbsu
.Op Fl m Ar message
.Op Fl u Ar user
.Ar command
.br
.Nm dsbsu
.Fl a
.Op Fl c Ar command
.br
.Nm dsbsudo
.Op Ar sudo options
.Ar command
.Op Ar args ...

.Sh OPTIONS
.Bl -tag -width indent
.It Fl a
Writes the entered password to stdout, and exits.
.It Fl c
Shows the given
.Ar command
string in the password window.
.It Fl m
Shows the given
.Ar message
in the password window.
.It Fl u
Runs the
.Ar command
as the given
.Ar user .
If
.Fl u
is not defined, root is assumed.

